# conda_replicAnt.yml

# replicAnt - Fabi And René's Training-data Synthesizer
# © Fabian Plum, René Bulla 2023
# MIT License

name: replicAnt
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - matplotlib
  - opencv
  - json5
  - pandas
  - pathlib
  - imutils
  - scikit-learn